datasource:
  db-cooperation:
    hikari:
      driver-class-name: org.postgresql.Driver
      jdbc-url: "${DATASOURCE_URL}"
      username: "${DATASOURCE_USERNAME}"
      password: "${DATASOURCE_PASSWORD}"
      connection-timeout: 60000
      maximum-pool-size: 5
spring:
  liquibase:
    enabled: true
    change-log: classpath:db.changelog-master.xml
    drop-first: false
salary:
  amount:
    engineer:
      base: 10000
      grade: 2000
    worker:
      base: 9000
      grade: 1000
    manager:
      base: 15000
      grade: 3000
  tax:
    medical: 5.1
    ndfl: 13
    social: 2.9
    retirement: 22
  vacation:
    days: 28
frontend:
  host: "${SALARY_FRONTEND_URL}"
app:
  job-properties:
    calculate-salary:
      fixed-delay: 50000
      initial-delay: 5000
      limit: 100
